# Testing our Docker-based configuration under TravisCI,
# based on https://docs.travis-ci.com/user/docker/ and
# selected other real-world repositories on GitHub.
#

language: bash
os: linux
sudo: required

services:
  - docker

script:
  - docker build .
